---
kind: pipeline
type: kubernetes
name: Build and Deploy

clone:
  skip_verify: true

trigger:
  branch:
  - master

steps:
  - name: Build
    image: squidfunk/mkdocs-material
    # environment:
    #   SPOTIFY_CACHE:
    #     from_secret: SPOTIFY_CACHE
    commands:
    - build
    - ls -la docs
    - ls -la .


#  - name: Build Docker Image
#    image: plugins/docker
#    privileged: false
#    #    image: banzaicloud/drone-kaniko
#    failure: ignore
#    settings:
#      repo: n.lahmi/spotilike
#      tags: latest
#      registry: registry-svc.default.svc.cluster.local:3000
##      registry: registry.k
#      insecure: true
##      custom_dns: 8.8.8.8
#      debug: true
#      ipv6: false
#      build_args: --network host

  - name: Build Docker Image
    image: plugins/docker
#    privileged: false
    settings:
      repo: registry.k/n.lahmi/spotilike
      tags: latest
      registry: registry.k
      insecure: true
      ipv6: false
      experimental: no
      mtu: 1450
